name: Deployment
on:
  release:
    types: [published]
jobs:
  tests:
    name: Deploy to wordpress
    runs-on: ubuntu-latest
    environment:
      name: Deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install gettext
        run: |
          sudo apt-get update
          sudo apt-get install gettext
      - name: Build
        run: ./scripts/build.sh
      - name: Deploy plugin
        env:
          WP_ORG_PASSWORD: ${{ secrets.WP_ORG_PASSWORD }}
        run: ./scripts/deploy.sh "${WP_ORG_PASSWORD}"
